spring.application.name=proyectofinal

# H2 (memoria)
spring.datasource.url=jdbc:h2:mem:seguridaddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Ejecutar data.sql luego de crear tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false

